config/routes.rb
Flyfire::Application.routes.draw do
  get "home/intro"
  apipie

  get '/items/:id/select' => 'items#select'

  resources :items
  post '/api/createFromAPI/' => 'items#createFromAPI'

  get "welcome/index/:side" => "welcome#index"
  get "welcome/index"

  root 'welcome#intro'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @item = Item.new
    @items = Item.find(:all, :order => "picture")
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  def select
    @item = Item.find(params[:id])
    @item.touch
    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { redirect_to items_url }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end
  api :POST, '/api/createFromAPI/'
  param :color, String, "screen color"
  param :picture, String, "picture url"
  formats ['json']
  def createFromAPI
    puts params.to_json
    @item = Item.new()
    @item.color = params[:color]
    @item.picture = params[:picture]
    @item.save
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:color, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @item = Item.order("updated_at").last
    if @item.picture == "http://auto.img.v4.skyrock.net/8114/67818114/pics/2712393530_small_1.png"
      if params[:side] =="left"
        @item.color = "#000000"
      else
        @item.color = "red"
      end

    end
  end
  def intro

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<br/>
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    color: <%= f.text_field :color, :style =>"width:201px;" %>
  </div>
  <div class="field">
    Picture: <%= f.text_field :picture %>
  </div>
  <div class="field">
    Vibrate? <%= check_box_tag :vibrate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#item_color').minicolors();
</script>

app/views/items/createFromAPI.html.erb
OK

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <div class="itemContainer">
    <a href="/items/<%= item.id%>/select/">
      <div class="item" style="background-color:<%= item.color%>">
        <% if item.picture != nil%>
          <img src="<%=item.picture%>" style="max-height:100%" height="100%" width="100%"/>
        <%end%>
      </div>
    </a>
    <%= button_to "X", item, :method => :delete, :confirm => "Are you sure?", :class=>"destroyItem"  %>
  </div>
<% item.color %>
<% item.picture %>
<% link_to 'Show', item %>
<% link_to 'Edit', edit_item_path(item) %>


<% end %>

<br/><br/><br/><br/><br/><br/><br/>

<div style="width:300px; border:1px solid black; margin-left:20px;" class="addBox">
  <%= render 'form' %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @item.color %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @item.picture %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flyfire</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag params[:controller].split("/")[0] %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="background" style="background-color:<%= @item.color%>; height:100%;width:100%; position: absolute;">

  <% if @item.picture != nil%>
    <img src="<%= @item.picture%>" style="width: 100%;max-height: 100%"/>
  <%end%>
</div>

<% if params[:norefresh] != "true"%>
<script>
  $(document).ready(function() {
    return setTimeout((function() {
      window.location.reload(1);
    }), 1000);
  });

</script>
<%end%>

<%= @item.to_json%>
<% if @item.vibrate == true %>
  <script>
    $(document).ready(function() {
      window.navigator = window.navigator || {};
      navigator.vibrate(1000);
      navigator.vibrate(10000);
    });
  </script>
<%end%>

app/views/welcome/intro.html.erb
<a style="background-color:red;width:50%; float:left; height:100%; position:absolute; text-size:8em;padding-top:200px;padding-left:20px;" href="/welcome/index/left"><img width="95%" src="/leftSelect.png"/></a>
<a style="background-color:black;margin-left:50%;width:50%; height:100%; position:absolute;padding-top:200px;padding-left:20px;" href="/welcome/index/right"><img width="95%" src="/rightSelect.png"/></a>